os: osx
sudo: required
language: node_js
node_js:
  - "6"

#blocklist
branches:
  except:
    - gh-pages

cache:
  yarn: true
  directories:
  - node_modules

# Environment setup
before_install:
  # Install FontForge
  - brew install ttfautohint fontforge --with-python

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

# Build
script:
  - yarn build

# Deploy
deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
    file:
      - dist/tangram_icons-design.zip
